Add routes
Mariya-Sharibchenko/react-project pull request #45
Opened 2022-04-13 12:55 UTC by Mariya-Sharibchenko

2022-04-13 15:23 UTC, Karador approved these changes

2022-04-16 10:37 UTC, suicaed requested changes
Well done, but it is not understandable about array with some numbers, check the comment.

2022-04-16 10:37 UTC, suicaed commented on src/pages/Company/CompanyTemplate.tsx
> +          element={<HomePage students={StudentArray} studentsInBookmarks={[2,1,5]} />}
What is `[2,1,5]`?

2022-04-18 07:44 UTC, Mariya-Sharibchenko commented on src/pages/Company/CompanyTemplate.tsx
> +          element={<HomePage students={StudentArray} studentsInBookmarks={[2,1,5]} />}
just mock data, fixed

2022-04-22 07:55 UTC, merged